language: ruby
rvm:
  - 1.9.3
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.4
  - 2.6.2
before_install: "gem update bundler"
cache: bundler
script: "bundle exec rake test"
notifications:
  email: false
sudo: false
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6_edge.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_6_edge.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_6_edge.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_6_edge.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/rails_6_edge.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails_6_edge.gemfile
