language: ruby
rvm:
  - 1.9.3
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
before_install: "gem update bundler"
cache: bundler
script: "bundle exec rake test"
notifications:
  email: false
sudo: false
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5_edge.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_edge.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_edge.gemfile
